[package]
name = "xox-random"
version = "0.1.0"
edition = "2021"

[dependencies]
getrandom = "0.2.8"

[dev-dependencies]
expect-test = "1.4.0"
trivium = { git = "https://github.com/apribadi/trivium" }
